resource_group_location    = "Central US"
resource_group_name        = "terraform-aks"
environment                = "dev"
ssh_public_key             = ".ssh_keys/askprodkeys.pub"
windows_admin_username     = "azureuser"
windows_admin_password     = "P@ssw0rd1234"
